ARG STAGE

# build stage
FROM node:14.19.3-alpine AS build_stage
WORKDIR /app
COPY package*.json ./
COPY yarn.lock ./
RUN yarn --ignore-engines
COPY . .
RUN yarn run build:stg

# copy files and nginx conf
FROM nginx:stable-alpine AS publish_site
COPY  ./.nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=build_stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]